#!/bin/sh

# @category install script
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

######## CONFIG ##########################################################################
export vendor=vendor/bermud-ru/phprest
export serverRoot=$(pwd)
export PROJECT=${PWD##*/}
export DOMAIN=$(jq -r .install.domain ./composer.json)
##########################################################################################
echo "Post-install scripting ..."
cp -rf ./$vendor/public/* ./public/
cp -rf ./$vendor/config.php ./

exit