#!/bin/sh

# @category install script
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015

######## CONFIG ##########################################################################
export vendor=vendor/bermud-ru/phproll
export serverRoot=$(pwd)
export PROJECT=${PWD##*/}
export DOMAIN=$(jq .install.project ./composer.json)
##########################################################################################
echo "Post-update scripting ..."

printf "WEB context resotre\n"
chcon -R -t httpd_sys_content_t $serverRoot
semanage fcontext -a -t httpd_sys_content_t "${serverRoot}/(/.*)?"

exit
