#!/bin/sh

# @category install script
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015

echo "Post-install scripting ..."
mkdir -p ./public/css
mkdir -p ./public/js
mkdir -p ./Application/view
mkdir -p ./Application/models
cp -rf ./vendor/bermud-ru/phprest/public/401.html ./public/
cp -rf ./vendor/bermud-ru/phprest/public/500.html ./public/
cp -rf ./vendor/bermud-ru/phprest/public/fivicon.ico ./public/
cp -rf ./vendor/bermud-ru/phprest/public/index.php ./public/
cp -rf ./vendor/bermud-ru/phprest/public/robots.txt ./public/
cp -rf ./vendor/bermud-ru/phprest/config.php ./
cp -n ./vendor/bermud-ru/phprest/public/css/* ./public/css/
#cp -rf ./vendor/bermud-ru/phprest/public/js/* ./public/js/
for js in ./vendor/bermud-ru/phprest/public/js/*
do
 [ -f $js ] && cp -rf $js ./public/js/
done
cp -rf ./vendor/bermud-ru/phprest/Application/view/* ./Application/view/
cp -rf ./vendor/bermud-ru/phprest/Application/models/* ./Application/models/