#!/bin/sh

# @category install script
# @author Андрей Новиков <andrey@novikov.be>
# @data 07/12/2015

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

######## CONFIG ##########################################################################
export vendor=vendor/bermud-ru/phprest
export serverRoot=$(pwd)
export PROJECT=${PWD##*/}
export DOMAIN=$(jq .install.project ./composer.json)
##########################################################################################
echo "Post-update scripting ..."

printf "WEB context resotre\n"
chcon -R -t httpd_sys_content_t $serverRoot
semanage fcontext -a -t httpd_sys_content_t "${serverRoot}/(/.*)?"

exit
